import { Transaction, Budget, SavingsGoal, CashFlowPoint, UserProfile, ProjectFolder } from './types';

export const INITIAL_PROJECTS: ProjectFolder[] = [
  {
    id: 'proj-sap',
    name: 'SAP S/4HANA Enterprise Migration',
    code: 'PRJ-SAP-2026',
    description: 'Q3 Enterprise ERP vendor settlements, cloud infrastructure & consulting invoices',
    department: 'Engineering & IT',
    allocatedBudget: 1500000,
    color: '#0284C7',
    createdAt: '2026-09-01',
  },
  {
    id: 'proj-bengaluru',
    name: 'Bengaluru Tech Park Expansion',
    code: 'PRJ-BLR-104',
    description: 'Campus lease, fit-outs, workstation procurements, and utility deposits',
    department: 'Operations & Facilities',
    allocatedBudget: 2800000,
    color: '#10B981',
    createdAt: '2026-09-05',
  },
  {
    id: 'proj-cloud',
    name: 'Cloud Infrastructure & AI Ops',
    code: 'PRJ-OPS-77',
    description: 'AWS GPU clusters, Gemini AI API tier, and high-availability leased lines',
    department: 'Platform Engineering',
    allocatedBudget: 950000,
    color: '#6366F1',
    createdAt: '2026-09-10',
  },
];

export const INITIAL_USER: UserProfile = {
  name: 'Durga Prasad',
  email: 'durga@finflow.ai',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  currency: 'INR',
  locale: 'en-IN',
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-101',
    merchant: 'Razorpay Technologies (Salary)',
    category: 'Salary & Bonus',
    date: '2026-09-01',
    amount: 285000,
    type: 'INCOME',
    status: 'Completed',
    note: 'Monthly Senior Tech Lead compensation',
    account: 'HDFC Salary A/C - 4821',
    projectId: 'proj-sap',
  },
  {
    id: 'tx-102',
    merchant: 'Godrej Properties (Apartment Rent)',
    category: 'Housing',
    date: '2026-09-03',
    amount: 58000,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'September luxury 3BHK lease',
    account: 'HDFC Salary A/C - 4821',
    projectId: 'proj-bengaluru',
  },
  {
    id: 'tx-103',
    merchant: 'Zerodha Broking (Quarterly Dividend)',
    category: 'Investments',
    date: '2026-09-05',
    amount: 34500,
    type: 'INCOME',
    status: 'Completed',
    note: 'Nifty 50 Index + TCS yield payout',
    account: 'ICICI Direct Wealth - 9912',
  },
  {
    id: 'tx-104',
    merchant: 'Nature Basket & BigBasket Instant',
    category: 'Groceries',
    date: '2026-09-07',
    amount: 12450,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'Organic produce, imported pantry staples',
    account: 'Axis Magnus Card - 7721',
  },
  {
    id: 'tx-105',
    merchant: 'Blue Tokai Coffee Roasters',
    category: 'Dining & Drinks',
    date: '2026-09-09',
    amount: 2840,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'Specialty pour-overs with engineering team',
    account: 'HDFC Millennia - 3314',
  },
  {
    id: 'tx-106',
    merchant: 'Tata Power Electricity Board',
    category: 'Utilities',
    date: '2026-09-11',
    amount: 6720,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'EV charger & residential electricity bill',
    account: 'HDFC Salary A/C - 4821',
  },
  {
    id: 'tx-107',
    merchant: 'Uber Premier Intercity',
    category: 'Transportation',
    date: '2026-09-12',
    amount: 3200,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'Airport transit to Bengaluru tech summit',
    account: 'Axis Magnus Card - 7721',
  },
  {
    id: 'tx-108',
    merchant: 'Substack & Tech Consulting',
    category: 'Freelance',
    date: '2026-09-14',
    amount: 45000,
    type: 'INCOME',
    status: 'Completed',
    note: 'Distributed systems architecture audit advisory',
    account: 'HDFC Salary A/C - 4821',
  },
  {
    id: 'tx-109',
    merchant: 'Apple Store BKC (AirPods Max 2)',
    category: 'Shopping',
    date: '2026-09-16',
    amount: 54900,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'Noise-canceling headphones for focus work',
    account: 'Axis Magnus Card - 7721',
  },
  {
    id: 'tx-110',
    merchant: 'Cult.fit & Peak Performance Gym',
    category: 'Healthcare',
    date: '2026-09-18',
    amount: 18500,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'Annual premium gym & recovery pass',
    account: 'HDFC Millennia - 3314',
  },
  {
    id: 'tx-111',
    merchant: 'Bastian Bandra Dining',
    category: 'Dining & Drinks',
    date: '2026-09-20',
    amount: 14200,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'Anniversary celebration dinner',
    account: 'Axis Magnus Card - 7721',
  },
  {
    id: 'tx-112',
    merchant: 'Netflix Premium 4K + Spotify',
    category: 'Entertainment',
    date: '2026-09-22',
    amount: 1499,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'Monthly streaming subscriptions',
    account: 'HDFC Millennia - 3314',
  },
  {
    id: 'tx-113',
    merchant: 'Apollo Pharmacy & Diagnostics',
    category: 'Healthcare',
    date: '2026-09-24',
    amount: 4350,
    type: 'EXPENSE',
    status: 'Completed',
    note: 'Quarterly health diagnostics & vitamins',
    account: 'Axis Magnus Card - 7721',
  },
  {
    id: 'tx-114',
    merchant: 'Taj Fort Aguada Goa (Upcoming Stay)',
    category: 'Entertainment',
    date: '2026-09-25',
    amount: 42000,
    type: 'EXPENSE',
    status: 'Pending',
    note: 'Long weekend sea view villa reservation',
    account: 'Axis Magnus Card - 7721',
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'b-1',
    category: 'Housing',
    allocatedAmount: 65000,
    spentAmount: 58000,
    period: 'Monthly',
    color: '#6366F1',
  },
  {
    id: 'b-2',
    category: 'Groceries',
    allocatedAmount: 25000,
    spentAmount: 18450,
    period: 'Monthly',
    color: '#10B981',
  },
  {
    id: 'b-3',
    category: 'Dining & Drinks',
    allocatedAmount: 20000,
    spentAmount: 17040,
    period: 'Monthly',
    color: '#F59E0B',
  },
  {
    id: 'b-4',
    category: 'Transportation',
    allocatedAmount: 12000,
    spentAmount: 8200,
    period: 'Monthly',
    color: '#0284C7',
  },
  {
    id: 'b-5',
    category: 'Shopping',
    allocatedAmount: 40000,
    spentAmount: 54900, // over-budget to test alerting visual
    period: 'Monthly',
    color: '#EC4899',
  },
  {
    id: 'b-6',
    category: 'Healthcare',
    allocatedAmount: 25000,
    spentAmount: 22850,
    period: 'Monthly',
    color: '#F43F5E',
  },
];

export const INITIAL_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'sg-1',
    title: 'Emergency Liquidity Reserve (6 Mo)',
    currentAmount: 950000,
    targetAmount: 1200000,
    targetDate: '2026-12-31',
    category: 'Security',
  },
  {
    id: 'sg-2',
    title: 'Kyoto & Tokyo Autumn Tour',
    currentAmount: 380000,
    targetAmount: 450000,
    targetDate: '2026-11-15',
    category: 'Travel',
  },
  {
    id: 'sg-3',
    title: 'MacBook Pro M4 Max Studio',
    currentAmount: 320000,
    targetAmount: 320000, // 100% completed to showcase celebration
    targetDate: '2026-10-01',
    category: 'Tech',
    isCompleted: true,
  },
];

export const CASH_FLOW_SERIES: CashFlowPoint[] = [
  { date: '2026-04', label: 'Apr', income: 320000, expense: 195000, net: 125000 },
  { date: '2026-05', label: 'May', income: 345000, expense: 210000, net: 135000 },
  { date: '2026-06', label: 'Jun', income: 310000, expense: 182000, net: 128000 },
  { date: '2026-07', label: 'Jul', income: 390000, expense: 235000, net: 155000 },
  { date: '2026-08', label: 'Aug', income: 360000, expense: 205000, net: 155000 },
  { date: '2026-09', label: 'Sep', income: 364500, expense: 224369, net: 140131 },
];

export const INITIAL_CLAIMS = [
  {
    id: 'CLM-2026-081',
    employeeName: 'Raghav Sharma',
    employeeId: 'EMP-1042',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=128',
    department: 'Engineering' as const,
    claimType: 'WFH Tech Setup' as const,
    amount: 14500,
    submittedDate: '2026-09-24',
    status: 'PENDING_APPROVAL' as const,
    approver: 'Durga Prasad (HR Lead)',
    notes: 'Ergonomic dual-monitor desk arm and mechanical keyboard receipt',
  },
  {
    id: 'CLM-2026-082',
    employeeName: 'Ananya Iyer',
    employeeId: 'EMP-1088',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=128',
    department: 'Sales & Marketing' as const,
    claimType: 'Travel & Client Transit' as const,
    amount: 28400,
    submittedDate: '2026-09-23',
    status: 'PENDING_APPROVAL' as const,
    approver: 'Durga Prasad (HR Lead)',
    notes: 'Bengaluru client roadshow flights & hotel accommodation',
  },
  {
    id: 'CLM-2026-083',
    employeeName: 'Vikram Malhotra',
    employeeId: 'EMP-1115',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=128',
    department: 'Product' as const,
    claimType: 'Client Entertainment' as const,
    amount: 9200,
    submittedDate: '2026-09-21',
    status: 'APPROVED' as const,
    approver: 'Durga Prasad (HR Lead)',
    notes: 'Strategic enterprise partner lunch meeting in Bandra Kurla Complex',
  },
  {
    id: 'CLM-2026-084',
    employeeName: 'Priya Nair',
    employeeId: 'EMP-1056',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=128',
    department: 'People & Culture' as const,
    claimType: 'Learning & Certification' as const,
    amount: 18000,
    submittedDate: '2026-09-18',
    status: 'DISBURSED' as const,
    approver: 'Finance Ops',
    notes: 'SHRM-CP People Operations annual exam fee & materials',
  },
  {
    id: 'CLM-2026-085',
    employeeName: 'Aditya Verma',
    employeeId: 'EMP-1099',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=128',
    department: 'Engineering' as const,
    claimType: 'Medical & Wellness' as const,
    amount: 6500,
    submittedDate: '2026-09-24',
    status: 'PENDING_APPROVAL' as const,
    approver: 'Durga Prasad (HR Lead)',
    notes: 'Prescription eyewear & optical diagnostics reimbursement',
  },
  {
    id: 'CLM-2026-086',
    employeeName: 'Sneha Patel',
    employeeId: 'EMP-1132',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=128',
    department: 'Operations' as const,
    claimType: 'Travel & Client Transit' as const,
    amount: 12800,
    submittedDate: '2026-09-20',
    status: 'APPROVED' as const,
    approver: 'Durga Prasad (HR Lead)',
    notes: 'Warehouse logistics audit intercity cab transit & tolls',
  },
];

export const INITIAL_PAYROLL_RUNS = [
  {
    id: 'PAY-2026-09',
    month: 'September 2026',
    totalEmployees: 142,
    grossPayroll: 5840000,
    netDisbursed: 4720000,
    taxPfWithheld: 1120000,
    status: 'SCHEDULED' as const,
    disbursementDate: '2026-09-30',
  },
  {
    id: 'PAY-2026-08',
    month: 'August 2026',
    totalEmployees: 138,
    grossPayroll: 5680000,
    netDisbursed: 4590000,
    taxPfWithheld: 1090000,
    status: 'DISBURSED' as const,
    disbursementDate: '2026-08-31',
  },
  {
    id: 'PAY-2026-07',
    month: 'July 2026',
    totalEmployees: 135,
    grossPayroll: 5420000,
    netDisbursed: 4380000,
    taxPfWithheld: 1040000,
    status: 'DISBURSED' as const,
    disbursementDate: '2026-07-31',
  },
];

